[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[window]
opacity = 1
blur = true

[terminal]

[terminal.shell]
program = "/usr/bin/fish"

[cursor]
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.5
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.4
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 2.0
smooth_motion_max_stretch_y = 2.0
# Override "block" cursor if you don't like how it looks in this fork
#block_replace_shape = "underline"
